<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <BR>
    <h1><CENTER><B><?php echo $location ;?></B></CENTER></h1><BR><BR>
 <CENTER>   <a href="current?loc=<?php echo $location ?>" class="btn btn-primary">KNOW CURRENT WEATHER</a><br><br>
    <a href="forecast?loc=<?php echo $location ?>" class="btn btn-primary">KNOW FORECAST</a><br><br>
    <a href="current?loc=<?php echo $location ?>" class="btn btn-primary">KNOW HISTORY</a><br><br>
    <a href="timezone?loc=<?php echo $location ?>" class="btn btn-primary">KNOW TIMEZONE</a><br><br>
    <a href="sports?loc=<?php echo $location ?>" class="btn btn-primary">KNOW SPORTS</a><br><br>
    <a href="astronomy?loc=<?php echo $location ?>" class="btn btn-primary">KNOW ASTRONOMY</a><br><br>
    <!-- <a href="#" class="btn btn-primary">KNOW HISTORY</a><br><br> -->
    <a href="current?loc=<?php echo $location ?>" class="btn btn-primary">KNOW WEATHER ALERTS</a><br><br>
    <a href="airquality?loc=<?php echo $location ?>" class="btn btn-primary">KNOW AIR QUALITY</a><br><br></CENTER>

</body>
</html>