<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>

<h1>USING APIs</h1><br><br>
<form method="POST" action="index/search">
<div class="input-group">
  <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" name="search" aria-describedby="search-addon" />
  <button type="submit" class="btn btn-outline-primary">search</button>
</div>
</form>
    
</body>

</html>