    <!-- Product section-->
    <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6" ><img class="card-img-top mb-5 mb-md-0" src="<?php echo $url; ?>"  width="500px" height="600px" /></div>
                    <div class="col-md-6">
                        <h1 class="display-5 fw-bolder"><?php echo $details->title; ?></h1>
                        <p class="lead"><?php echo $details->description; ?></p>
                    </div>
                </div>
            </div>
        </section>
       
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">&copy; CEDCOSS Technologies</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>